[package]
name = "rawdaw-synth-drum"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
rawdaw-dsp = { path = "../rawdaw-dsp" }
rawdaw-engine = { path = "../rawdaw-engine" }
rawdaw-model = { path = "../rawdaw-model" }
